cluster:
  name: ${ELASTICSEARCH_CLUSTERNAME}
  routing.allocation:
    node_initial_primaries_recoveries: 4
  routing.allocation:
    node_concurrent_recoveries: 2

node:
  name: ${ELASTICSEARCH_NODENAME}
  master: true
  data: true
  rack: ${ELASTICSEARCH_RACK}

index:
  number_of_shards: ${ELASTICSEARCH_SHARDS}
  number_of_replicas: ${ELASTICSEARCH_REPLICAS}

network:
  bind_host: 0.0.0.0
  publish_host: ${ELASTICSEARCH_PUBLISH_HOST}

transport:
  tcp:
    port: ${ELASTICSEARCH_TCP_PORT}
    compress: true

http:
  port: ${ELASTICSEARCH_HTTP_PORT}
  max_content_length: 100mb
  enabled: true

indices:
  recovery:
    max_size_per_sec: 100mb
    concurrent_streams: 5

discovery:
  zen:
    minimum_master_nodes: 1
    ping:
      timeout: 10s
      multicast:
        enabled: false
      unicast:
        hosts: ${ELASTICSEARCH_UNICAST_HOSTS}
